### PR TITLE
license: dual license under cc-by-4 and mit

### PR DESCRIPTION
**Pull request by perigoso**
I would like to dual license the library so it is more flexible for everyone and their needs, but I would like to have the explicit authorization of every contributor so far as I'm not the sole copyright holder

- [x] @obra 
- [x] @Lotier 

Signed-off-by: Rafael Silva <perigoso@riseup.net>

### CODE REVIEW

**Comment by Lotier** [comment]
My authorization is given.

**Comment by obra** [comment]
Would you consider licensing under the MIT license? I don't think footprint should have place any restrictions on the boards folks make.

**Comment by perigoso** [comment]
yes, that actually makes more sense here

**Comment by Lotier** [comment]
I also 100% consent to an MIT license.

**Pull request merged**
